/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.logs.SzLog', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.logs.SzLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.logs.SzLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.logs.SzLog.displayName = 'proto.logs.SzLog';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.logs.SzLog.prototype.toObject = function(opt_includeInstance) {
  return proto.logs.SzLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.logs.SzLog} msg The msg instance to transform.
 * @return {!Object}
 */
proto.logs.SzLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    szServiceName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    szMessage: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hostname: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.logs.SzLog}
 */
proto.logs.SzLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.logs.SzLog;
  return proto.logs.SzLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.logs.SzLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.logs.SzLog}
 */
proto.logs.SzLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzServiceName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSzMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHostname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.logs.SzLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.logs.SzLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.logs.SzLog} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.logs.SzLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSzServiceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSzMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHostname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string sz_service_name = 1;
 * @return {string}
 */
proto.logs.SzLog.prototype.getSzServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.logs.SzLog.prototype.setSzServiceName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string sz_message = 2;
 * @return {string}
 */
proto.logs.SzLog.prototype.getSzMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.logs.SzLog.prototype.setSzMessage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string hostname = 3;
 * @return {string}
 */
proto.logs.SzLog.prototype.getHostname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.logs.SzLog.prototype.setHostname = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.logs);
